# Generated by Django 5.2.9 on 2025-12-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='type',
        ),
        migrations.AddField(
            model_name='discipline',
            name='exam_type',
            field=models.CharField(default='Экзамен', max_length=50),
        ),
        migrations.AddField(
            model_name='discipline',
            name='hours',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='discipline',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.specialty'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
