# Generated by Django 5.2.9 on 2025-12-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_discipline_type_discipline_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1, verbose_name='Роль'),
        ),
    ]
