# Generated by Django 5.2.9 on 2025-12-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.semester', verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='exam_type',
            field=models.CharField(max_length=50, verbose_name='Тип контроля'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='hours',
            field=models.IntegerField(verbose_name='Часы'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.specialty'),
        ),
    ]
