# Generated by Django 5.2.9 on 2025-12-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_discipline_exam_type_alter_discipline_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesheet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.teacher'),
        ),
    ]
