# Generated by Django 5.2.9 on 2025-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_gradesheet_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Сотрудник учебного отдела'), (2, 'Сотрудник дирекции'), (3, 'Преподаватель')], default=1, verbose_name='Роль'),
        ),
    ]
