# Generated by Django 5.2.9 on 2025-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_user_first_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='hours',
            field=models.PositiveIntegerField(default=72, verbose_name='Часы'),
        ),
    ]
